#!/bin/bash
source "/home/deploy/.pythonbrew/etc/bashrc"
pythonbrew use 2.7.2
pythonbrew venv use openparty-production

PROJDIR="/home/openparty/sites/openparty-app/releases/current/"

PIDFILE="/home/openparty/sites/openparty-app/openparty.pid"
if [ -f $PIDFILE ]; then
#   kill -9 `cat -- $PIDFILE`
   rm -f -- $PIDFILE
fi

kill -9 `ps aux|grep python|grep runfcgi|grep openparty-app|awk '{print $2}'`

cd $PROJDIR
# exec python ./manage.py runfcgi daemonize=false host=127.0.0.1 port=9090 pidfile=$PIDFILE --settings=settings
exec python ./manage.py runfcgi host=127.0.0.1 port=9090 pidfile=$PIDFILE method=prefork maxrequests=600 maxspare=2 minspare=1 maxchildren=3 --settings=settings

deactivate
pythonbrew off
